### ISSUE TITLE
Loading the instance config should be more robust

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-providers#399]
### What needs to get done

Extra fields should probably be allowed in the [instance config](https://github.com/canonical/craft-providers/blob/c9ba62bd8f551c6486b1beaa46b1cf024018b005/craft_providers/instance_config.py#L52C11-L52C11).

Or if the pydantic model fails, then the instance should be automatically cleaned.

### Why it needs to get done

If a user creates a charm with charmcraft 2.4.1, the instance config will look like this:
```
compatibility-tag: charmcraft-buildd-base-v1.0
setup: true
snaps:
  charmcraft:
    revision: "100"
```

If the user switches to charmcraft 2.2, config loading will fail because the `setup` tag is not in the pydantic model of the older version of craft-providers.

Ironically, if craft-providers had been able to load the config, it would have seen the compatibility tag did not match and would have triggered an automatic cleaning.

source: https://github.com/canonical/charmcraft/issues/1258
